# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view

# Copyright (c) 2020, Phytec Messtechnik GmbH, Peter Johanson
# SPDX-License-Identifier: Apache-2.0

description: IL0323 EPD display controller

compatible: "gooddisplay,il0323"

include: spi-device.yaml

properties:
  height:
    type: int
    required: true
    description: Height in pixel of the panel driven by the controller

  width:
    type: int
    required: true
    description: Width in pixel of the panel driven by the controller

  reset-gpios:
    type: phandle-array
    required: true
    description: RESET pin.

      The RESET pin of GD7965 is active low.
      If connected directly the MCU pin should be configured
      as active low.

  dc-gpios:
    type: phandle-array
    required: true
    description: DC pin.

      The DC pin of GD7965 is active low (transmission command byte).
      If connected directly the MCU pin should be configured
      as active low.

  busy-gpios:
    type: phandle-array
    required: true
    description: BUSY pin.

      The BUSY pin of GD7965 is active low.
      If connected directly the MCU pin should be configured
      as active low.

  pwr:
    type: uint8-array
    required: true
    description: Power Setting (PWR) values

  cdi:
    type: int
    required: true
    description: VCOM and data interval value

  tcon:
    type: int
    required: true
    description: TCON setting value
